apiVersion: v1
kind: Namespace
metadata:
  name: simple-ns
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: simple-ns
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: simple-ns
  labels:
    app: simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: simple-app:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /id
              port: 8000
            periodSeconds: 5
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /id
              port: 8000
            periodSeconds: 5
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
